name: First Workflow
# Allows to manually start the workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Assalam u alikum :)"
      - name: Bye
        run: echo "Ma Assalama!"
